# Generated by Django 4.1.2 on 2022-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description2', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userswep',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
